services:
  db:
    image: postgres
    restart: always
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  front:
    build:
      dockerfile: Dockerfile
      context: ..
    ports:
      - 4321:4321
    depends_on:
      - db

volumes:
  pgdata: